/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrderFailedRouteImport } from './routes/order-failed'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as VerifyAccountRouteImport } from './routes/verify-account'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin.categories.index'
import { Route as AdminCouponsIndexRouteImport } from './routes/admin.coupons.index'
import { Route as AdminCouponsCouponIdRouteImport } from './routes/admin.coupons.$couponId'
import { Route as AdminCouponsNewRouteImport } from './routes/admin.coupons.new'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin.customers.index'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin.products.$productId'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderFailedRoute = OrderFailedRouteImport.update({
  id: '/order-failed',
  path: '/order-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyAccountRoute = VerifyAccountRouteImport.update({
  id: '/verify-account',
  path: '/verify-account',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsIndexRoute = AdminCouponsIndexRouteImport.update({
  id: '/coupons/',
  path: '/coupons/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsCouponIdRoute = AdminCouponsCouponIdRouteImport.update({
  id: '/coupons/$couponId',
  path: '/coupons/$couponId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsNewRoute = AdminCouponsNewRouteImport.update({
  id: '/coupons/new',
  path: '/coupons/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/order-failed': typeof OrderFailedRoute
  '/order-success': typeof OrderSuccessRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/verify-account': typeof VerifyAccountRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/coupons/$couponId': typeof AdminCouponsCouponIdRoute
  '/admin/coupons/new': typeof AdminCouponsNewRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/coupons/': typeof AdminCouponsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/order-failed': typeof OrderFailedRoute
  '/order-success': typeof OrderSuccessRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/verify-account': typeof VerifyAccountRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin/coupons/$couponId': typeof AdminCouponsCouponIdRoute
  '/admin/coupons/new': typeof AdminCouponsNewRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/coupons': typeof AdminCouponsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/order-failed': typeof OrderFailedRoute
  '/order-success': typeof OrderSuccessRoute
  '/register': typeof RegisterRoute
  '/shop': typeof ShopRoute
  '/verify-account': typeof VerifyAccountRoute
  '/wishlist': typeof WishlistRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/coupons/$couponId': typeof AdminCouponsCouponIdRoute
  '/admin/coupons/new': typeof AdminCouponsNewRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/coupons/': typeof AdminCouponsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/order-failed'
    | '/order-success'
    | '/register'
    | '/shop'
    | '/verify-account'
    | '/wishlist'
    | '/account/orders'
    | '/account/security'
    | '/account/settings'
    | '/admin/cms'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/orders'
    | '/products/$slug'
    | '/account/'
    | '/admin/coupons/$couponId'
    | '/admin/coupons/new'
    | '/admin/customers/$customerId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/categories/'
    | '/admin/coupons/'
    | '/admin/customers/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/order-failed'
    | '/order-success'
    | '/register'
    | '/shop'
    | '/verify-account'
    | '/wishlist'
    | '/account/orders'
    | '/account/security'
    | '/account/settings'
    | '/admin/cms'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/orders'
    | '/products/$slug'
    | '/account'
    | '/admin/coupons/$couponId'
    | '/admin/coupons/new'
    | '/admin/customers/$customerId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/contact'
    | '/login'
    | '/order-failed'
    | '/order-success'
    | '/register'
    | '/shop'
    | '/verify-account'
    | '/wishlist'
    | '/account/orders'
    | '/account/security'
    | '/account/settings'
    | '/admin/cms'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/orders'
    | '/products/$slug'
    | '/account/'
    | '/admin/coupons/$couponId'
    | '/admin/coupons/new'
    | '/admin/customers/$customerId'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/categories/'
    | '/admin/coupons/'
    | '/admin/customers/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  OrderFailedRoute: typeof OrderFailedRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  RegisterRoute: typeof RegisterRoute
  ShopRoute: typeof ShopRoute
  VerifyAccountRoute: typeof VerifyAccountRoute
  WishlistRoute: typeof WishlistRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-failed': {
      id: '/order-failed'
      path: '/order-failed'
      fullPath: '/order-failed'
      preLoaderRoute: typeof OrderFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-account': {
      id: '/verify-account'
      path: '/verify-account'
      fullPath: '/verify-account'
      preLoaderRoute: typeof VerifyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons/': {
      id: '/admin/coupons/'
      path: '/coupons'
      fullPath: '/admin/coupons/'
      preLoaderRoute: typeof AdminCouponsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons/$couponId': {
      id: '/admin/coupons/$couponId'
      path: '/coupons/$couponId'
      fullPath: '/admin/coupons/$couponId'
      preLoaderRoute: typeof AdminCouponsCouponIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons/new': {
      id: '/admin/coupons/new'
      path: '/coupons/new'
      fullPath: '/admin/coupons/new'
      preLoaderRoute: typeof AdminCouponsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AccountRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminCmsRoute: typeof AdminCmsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminCouponsCouponIdRoute: typeof AdminCouponsCouponIdRoute
  AdminCouponsNewRoute: typeof AdminCouponsNewRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCouponsIndexRoute: typeof AdminCouponsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCmsRoute: AdminCmsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminCouponsCouponIdRoute: AdminCouponsCouponIdRoute,
  AdminCouponsNewRoute: AdminCouponsNewRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCouponsIndexRoute: AdminCouponsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  OrderFailedRoute: OrderFailedRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  RegisterRoute: RegisterRoute,
  ShopRoute: ShopRoute,
  VerifyAccountRoute: VerifyAccountRoute,
  WishlistRoute: WishlistRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
